project:
  type: book
  output-dir: docs
resources:
  - CNAME

book:
  title: "Le Tour de France as a CSV File"
  author: "Thomas Camminady"
  date: "7/04/2023"
  chapters:
    - index.qmd
   
execute:
  daemon: true

toc: true
number-sections: false

format:
  html:
    theme: mint
    page-layout: article
    code-fold: true
    code-line-numbers: true